
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-shared-dapr-app-token
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-shared-dapr-app-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .daprAppToken }}"
  data:
    - secretKey: daprAppToken
      remoteRef:
        key: shared-dapr-app-token

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-shared-dapr-api-token
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-shared-dapr-api-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .appApiToken }}"
  data:
    - secretKey: appApiToken
      remoteRef:
        key: shared-dapr-api-token
