
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-shared-daprio-dapr-api-token
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-shared-daprio-dapr-api-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .daprioDaprApiToken }}"
  data:
    - secretKey: daprioDaprApiToken
      remoteRef:
        key: shared-daprio-dapr-api-token

---

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-shared-daprio-app-api-token
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-shared-daprio-app-api-token
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .daprioAppApiToken }}"
  data:
    - secretKey: daprioAppApiToken
      remoteRef:
        key: shared-daprio-app-api-token
