apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - shared-pod-data.yml
  - cezzis-prm-secret-store.yml
  - shared-prm-secret-store.yml
  - external-secrets-dapr-tokens.yml
