apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: shared-secret-store
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    azurekv:
      tenantId: "abc490e5-395b-4db1-9d9f-18434a45263d"
      vaultUrl: "https://kv-vec-eus-glo-shared-1.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          namespace: cezzis
          key: client-id
        clientSecret:
          name: azure-sp-credentials
          namespace: cezzis
          key: client-secret
